name: Convert and Deploy Resume

on:
  push:
    branches:
      - main  # Ensure this is your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install LaTeX and Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended pandoc

    - name: Convert LaTeX to HTML
      run: |
        mkdir output
        pandoc resume.tex -s -o output/index.html --from=latex --to=html5

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        cname: devinhadley.com  # Ensure CNAME is set correctly
